feat: add commitlint configs (#1921)

diff --git a/common/git-hooks/commit-msg b/common/git-hooks/commit-msg
--- a/common/git-hooks/commit-msg
+++ b/common/git-hooks/commit-msg
@@ -18,8 +18,10 @@
 
 # This example enforces that commit message should contain a minimum amount of
 # description text.
-if [ `cat $1 | wc -w` -lt 3 ]; then
-  echo ""
-  echo "Invalid commit message: The message must contain at least 3 words."
-	exit 1
-fi
+# if [ `cat $1 | wc -w` -lt 3 ]; then
+#   echo ""
+#   echo "Invalid commit message: The message must contain at least 3 words."
+# 	exit 1
+# fi
+ 
+node common/scripts/install-run-rush.js commitlint --edit $1
